:imagesdir: ./images
:stylesheet: daro-dark.css

= Trabajo Practico integrador


== Descripcion

La cuota se abona por adelantado, en efectivo o tarjeta de crédito. Si se abona con tarjeta de crédito existen promociones en 3 y 6 cuotas. 
La inscripción por primera vez en el club implica completar los datos de la ficha y presentar apto físico.
Posee un plantel propio de profesores, y en caso de ausencias recurre al listado de suplentes para cubrirlos.
Vencido el período de pago, automáticamente el socio no puede realizar actividades. 
Para retomar, debe pagar la cuota, y el plazo de pago comienza a correr a partir del día siguiente al vencimiento de la cuota.


Desarrollar diagramas de clases en plantuml de la siguiente funcionalidad:

* Registro de los socios y de los no socios
* Entrega de carnet y cobro de cuota mensual o diaria
* Listado diario de los socios que en la fecha les vence la cuota

== Diagrama de casos de uso

ifdef::env-github[]
[%collapsible]
endif::[]
ifndef::env-github[]
[%collapsible%open]
endif::[]
====

[plantuml, target=i2599146368, svg]
....
@startuml

!theme spacelab

:Cliente: as cli

:Administrativo: as adm

    (Registro) as (reg)
    (Pago) as (pago)
    (Entregar Carnet) as (entcar)
    (Reporte vencimientos del dia) as (vendia)
    (adm) --> (vendia)

(cli) -r-> (reg)
(reg) --> (pago)
(reg) <.r. (entcar)
(cli) -r-> (pago)


@enduml
....
====
ifdef::env-github[]
image::i2599146368.svg[] 
endif::[]

== Diagramas de clases

ifdef::env-github[]
[%collapsible]
endif::[]
ifndef::env-github[]
[%collapsible%open]
endif::[]
====

[plantuml, target=i880841834, svg]
....
@startuml

!theme spacelab

class Persona {
    -nombre: String
    -apellido: String
    -dni: String
}

class Socio {
    -nroCarnet: int
    -carnetEmitido: Boolean
    -fechaInscripcion: Date
    -cuotaDiaVencimiento: Int
    -cuotaFechaUltimoPago: Int
    -cuotas: Cuota[]
    +registrar(): Socio
    +pagar(cuota: Cuota): void
}


class NoSocio {
    -actividades: Actividad[]
    +registrar(): NoSocio
    +pagar(actividad: Actividad): void
}

class Actividad {
    -nombre: String
    -importe: Double
}

NoSocio *-- Actividad

Persona <|-- Socio
Persona <|-- NoSocio

class Cuota {
    -importe: Double
    -fechaVencimiento: Date
    -cantidadCuotas: Int
    -fechaPago: Date
    -medioPago: String
}

Socio *-- Cuota

@enduml
....

====

ifdef::env-github[]
image::i880841834.svg[] 
endif::[]


