name: ADOC to Github Convert

on:
  push:
    branches:
      - development
    paths:
      - "tpi/*.adoc"
      - ".github/workflows/asciidoc.yml"
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    name: adoc for github
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: gem install kroki
        run: gem install asciidoctor-kroki
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tpi
            tp1
            tools/kroki/docker-compose.yml
      - uses: reitzig/actions-asciidoctor@v2.0.1
        with:
          version: 2.0.18
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build and start services
        run: |
          cd tools/kroki
          docker compose up -d
          docker compose ps
      - name: execute asciidoctor compiler
        run: find -type f -name "*.adoc" -exec sh -c 'asciidoctor -r asciidoctor-kroki -a allow-uri-read -a kroki-fetch-diagram -a env-github "$0"' {} \;
      - name: rename files with hash
        run: |
          filesWithHash=($(find -type f | grep -E '.-[0-9a-f]{64}\..{3}$'))
          for file in "${filesWithHash[@]}"; do
            fileDelete=$(echo "$file" | awk -F'-' '{print $1}')"."${file##*.}
            echo "delete file "$fileDelete
            if [ -e "$fileDelete" ]; then
              rm $fileDelete
            else
              echo "File to delete $fileDelete does not exist."
            fi
          done
          for fileSource in "${filesWithHash[@]}"; do
            fileDestination=$(echo "$fileSource" | awk -F'-' '{print $1}')"."${fileSource##*.}
            echo "mv "$fileSource" "$fileDestination
            mv $fileSource $fileDestination
          done
      - name: list tpi/*.*
        run: ls *.* -l
      - name: tpi/images/*.*
        run: ls tpi/images/*.* -l
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: adoc-to-github
